version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile  # Ensure this matches the filename
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env 
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"